import csv

# Define new UFC fighters to add
new_fighters = [
    {"Name": "Dustin Poirier", "Division": "Lightweight", "Age": 34, "Wins": 28, "Losses": 7, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Max Holloway", "Division": "Featherweight", "Age": 31, "Wins": 23, "Losses": 7, "Title Reigns": 1, "Country": "USA"},
    {"Name": "Francis Ngannou", "Division": "Heavyweight", "Age": 37, "Wins": 17, "Losses": 3, "Title Reigns": 1, "Country": "Cameroon"},
    {"Name": "Stipe Miocic", "Division": "Heavyweight", "Age": 41, "Wins": 20, "Losses": 4, "Title Reigns": 2, "Country": "USA"},
    {"Name": "Henry Cejudo", "Division": "Bantamweight", "Age": 36, "Wins": 16, "Losses": 2, "Title Reigns": 2, "Country": "USA"},
    # Add more fighters here
    {"Name": "Kamaru Usman", "Division": "Welterweight", "Age": 34, "Wins": 20, "Losses": 2, "Title Reigns": 1, "Country": "Nigeria"},
    {"Name": "Jorge Masvidal", "Division": "Welterweight", "Age": 36, "Wins": 35, "Losses": 15, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Colby Covington", "Division": "Welterweight", "Age": 33, "Wins": 16, "Losses": 3, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Robert Whittaker", "Division": "Middleweight", "Age": 30, "Wins": 23, "Losses": 5, "Title Reigns": 1, "Country": "Australia"},
    {"Name": "Paulo Costa", "Division": "Middleweight", "Age": 30, "Wins": 13, "Losses": 1, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Tony Ferguson", "Division": "Lightweight", "Age": 37, "Wins": 25, "Losses": 6, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Justin Gaethje", "Division": "Lightweight", "Age": 32, "Wins": 22, "Losses": 3, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Michael Chandler", "Division": "Lightweight", "Age": 34, "Wins": 22, "Losses": 5, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Derrick Lewis", "Division": "Heavyweight", "Age": 35, "Wins": 25, "Losses": 7, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Curtis Blaydes", "Division": "Heavyweight", "Age": 30, "Wins": 14, "Losses": 3, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Jairzinho Rozenstruik", "Division": "Heavyweight", "Age": 32, "Wins": 11, "Losses": 2, "Title Reigns": 0, "Country": "Suriname"},
    {"Name": "Alexander Volkov", "Division": "Heavyweight", "Age": 32, "Wins": 33, "Losses": 8, "Title Reigns": 0, "Country": "Russia"},
    {"Name": "Alistair Overeem", "Division": "Heavyweight", "Age": 40, "Wins": 47, "Losses": 19, "Title Reigns": 0, "Country": "Netherlands"},
    {"Name": "Jan Blachowicz", "Division": "Light Heavyweight", "Age": 37, "Wins": 27, "Losses": 8, "Title Reigns": 1, "Country": "Poland"},
    {"Name": "Dominick Reyes", "Division": "Light Heavyweight", "Age": 30, "Wins": 12, "Losses": 2, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Thiago Santos", "Division": "Light Heavyweight", "Age": 36, "Wins": 21, "Losses": 8, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Glover Teixeira", "Division": "Light Heavyweight", "Age": 41, "Wins": 32, "Losses": 7, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Anthony Smith", "Division": "Light Heavyweight", "Age": 32, "Wins": 34, "Losses": 16, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Johnny Walker", "Division": "Light Heavyweight", "Age": 28, "Wins": 18, "Losses": 5, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Corey Anderson", "Division": "Light Heavyweight", "Age": 31, "Wins": 14, "Losses": 5, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Ryan Bader", "Division": "Light Heavyweight", "Age": 37, "Wins": 28, "Losses": 6, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Lyoto Machida", "Division": "Light Heavyweight", "Age": 42, "Wins": 26, "Losses": 11, "Title Reigns": 1, "Country": "Brazil"},
    {"Name": "Rafael dos Anjos", "Division": "Lightweight", "Age": 36, "Wins": 30, "Losses": 13, "Title Reigns": 1, "Country": "Brazil"},
    {"Name": "Kevin Lee", "Division": "Lightweight", "Age": 28, "Wins": 18, "Losses": 6, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Dan Hooker", "Division": "Lightweight", "Age": 31, "Wins": 20, "Losses": 9, "Title Reigns": 0, "Country": "New Zealand"},
    {"Name": "Paul Felder", "Division": "Lightweight", "Age": 36, "Wins": 17, "Losses": 6, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Edson Barboza", "Division": "Featherweight", "Age": 34, "Wins": 21, "Losses": 9, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Calvin Kattar", "Division": "Featherweight", "Age": 32, "Wins": 22, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Yair Rodriguez", "Division": "Featherweight", "Age": 28, "Wins": 13, "Losses": 2, "Title Reigns": 0, "Country": "Mexico"},
    {"Name": "Chan Sung Jung", "Division": "Featherweight", "Age": 33, "Wins": 16, "Losses": 6, "Title Reigns": 0, "Country": "South Korea"},
    {"Name": "Brian Ortega", "Division": "Featherweight", "Age": 29, "Wins": 15, "Losses": 1, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Zabit Magomedsharipov", "Division": "Featherweight", "Age": 29, "Wins": 18, "Losses": 1, "Title Reigns": 0, "Country": "Russia"},
    {"Name": "Jose Aldo", "Division": "Bantamweight", "Age": 34, "Wins": 29, "Losses": 7, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Petr Yan", "Division": "Bantamweight", "Age": 28, "Wins": 15, "Losses": 2, "Title Reigns": 1, "Country": "Russia"},
    {"Name": "Marlon Moraes", "Division": "Bantamweight", "Age": 32, "Wins": 23, "Losses": 8, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Cory Sandhagen", "Division": "Bantamweight", "Age": 28, "Wins": 14, "Losses": 2, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Aljamain Sterling", "Division": "Bantamweight", "Age": 31, "Wins": 20, "Losses": 3, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Sean O'Malley", "Division": "Bantamweight", "Age": 26, "Wins": 13, "Losses": 1, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Holly Holm", "Division": "Bantamweight", "Age": 39, "Wins": 14, "Losses": 5, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Germaine de Randamie", "Division": "Bantamweight", "Age": 36, "Wins": 10, "Losses": 4, "Title Reigns": 0, "Country": "Netherlands"},
    {"Name": "Aspen Ladd", "Division": "Bantamweight", "Age": 25, "Wins": 9, "Losses": 1, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Irene Aldana", "Division": "Bantamweight", "Age": 32, "Wins": 12, "Losses": 6, "Title Reigns": 0, "Country": "Mexico"},
    {"Name": "Ketlen Vieira", "Division": "Bantamweight", "Age": 29, "Wins": 11, "Losses": 1, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Julianna Pena", "Division": "Bantamweight", "Age": 31, "Wins": 10, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Raquel Pennington", "Division": "Bantamweight", "Age": 32, "Wins": 11, "Losses": 8, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Amanda Ribas", "Division": "Strawweight", "Age": 27, "Wins": 10, "Losses": 1, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Mackenzie Dern", "Division": "Strawweight", "Age": 27, "Wins": 10, "Losses": 1, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Tatiana Suarez", "Division": "Strawweight", "Age": 29, "Wins": 8, "Losses": 0, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Rose Namajunas", "Division": "Strawweight", "Age": 28, "Wins": 10, "Losses": 4, "Title Reigns": 1, "Country": "USA"},
    {"Name": "Weili Zhang", "Division": "Strawweight", "Age": 30, "Wins": 21, "Losses": 1, "Title Reigns": 1, "Country": "China"},
    {"Name": "Joanna Jedrzejczyk", "Division": "Strawweight", "Age": 33, "Wins": 16, "Losses": 4, "Title Reigns": 0, "Country": "Poland"},
    {"Name": "Jessica Andrade", "Division": "Strawweight", "Age": 29, "Wins": 21, "Losses": 8, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Claudia Gadelha", "Division": "Strawweight", "Age": 31, "Wins": 18, "Losses": 5, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Carla Esparza", "Division": "Strawweight", "Age": 33, "Wins": 17, "Losses": 6, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Michelle Waterson", "Division": "Strawweight", "Age": 34, "Wins": 18, "Losses": 8, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Marina Rodriguez", "Division": "Strawweight", "Age": 33, "Wins": 13, "Losses": 1, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Yan Xiaonan", "Division": "Strawweight", "Age": 31, "Wins": 13, "Losses": 1, "Title Reigns": 0, "Country": "China"},
    {"Name": "Angela Hill", "Division": "Strawweight", "Age": 35, "Wins": 13, "Losses": 9, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Tecia Torres", "Division": "Strawweight", "Age": 31, "Wins": 12, "Losses": 5, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Felice Herrig", "Division": "Strawweight", "Age": 36, "Wins": 14, "Losses": 9, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Randa Markos", "Division": "Strawweight", "Age": 35, "Wins": 10, "Losses": 10, "Title Reigns": 0, "Country": "Canada"},
    {"Name": "Alexa Grasso", "Division": "Flyweight", "Age": 27, "Wins": 13, "Losses": 3, "Title Reigns": 0, "Country": "Mexico"},
    {"Name": "Lauren Murphy", "Division": "Flyweight", "Age": 37, "Wins": 14, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Jessica Eye", "Division": "Flyweight", "Age": 34, "Wins": 15, "Losses": 8, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Cynthia Calvillo", "Division": "Flyweight", "Age": 33, "Wins": 9, "Losses": 2, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Katlyn Chookagian", "Division": "Flyweight", "Age": 31, "Wins": 15, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Jennifer Maia", "Division": "Flyweight", "Age": 32, "Wins": 18, "Losses": 7, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Roxanne Modafferi", "Division": "Flyweight", "Age": 38, "Wins": 25, "Losses": 18, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Andrea Lee", "Division": "Flyweight", "Age": 31, "Wins": 12, "Losses": 5, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Viviane Araujo", "Division": "Flyweight", "Age": 33, "Wins": 10, "Losses": 2, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Montana De La Rosa", "Division": "Flyweight", "Age": 25, "Wins": 11, "Losses": 6, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Maycee Barber", "Division": "Flyweight", "Age": 22, "Wins": 8, "Losses": 2, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Gillian Robertson", "Division": "Flyweight", "Age": 25, "Wins": 9, "Losses": 5, "Title Reigns": 0, "Country": "Canada"},
    {"Name": "Molly McCann", "Division": "Flyweight", "Age": 30, "Wins": 10, "Losses": 4, "Title Reigns": 0, "Country": "UK"},
    {"Name": "Ji Yeon Kim", "Division": "Flyweight", "Age": 31, "Wins": 9, "Losses": 3, "Title Reigns": 0, "Country": "South Korea"},
    {"Name": "Antonina Shevchenko", "Division": "Flyweight", "Age": 36, "Wins": 9, "Losses": 2, "Title Reigns": 0, "Country": "Kyrgyzstan"},
    {"Name": "Ariane Lipski", "Division": "Flyweight", "Age": 26, "Wins": 13, "Losses": 5, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Lina Lansberg", "Division": "Bantamweight", "Age": 38, "Wins": 10, "Losses": 5, "Title Reigns": 0, "Country": "Sweden"},
    {"Name": "Sarah Kaufman", "Division": "Bantamweight", "Age": 35, "Wins": 21, "Losses": 4, "Title Reigns": 0, "Country": "Canada"},
    {"Name": "Miesha Tate", "Division": "Bantamweight", "Age": 34, "Wins": 18, "Losses": 7, "Title Reigns": 1, "Country": "USA"},
    {"Name": "Ronda Rousey", "Division": "Bantamweight", "Age": 33, "Wins": 12, "Losses": 2, "Title Reigns": 1, "Country": "USA"},
    {"Name": "Cat Zingano", "Division": "Bantamweight", "Age": 38, "Wins": 11, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Bethe Correia", "Division": "Bantamweight", "Age": 37, "Wins": 11, "Losses": 5, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Marion Reneau", "Division": "Bantamweight", "Age": 43, "Wins": 9, "Losses": 7, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Yana Kunitskaya", "Division": "Bantamweight", "Age": 31, "Wins": 13, "Losses": 5, "Title Reigns": 0, "Country": "Russia"},
    {"Name": "Julia Avila", "Division": "Bantamweight", "Age": 32, "Wins": 8, "Losses": 2, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Pannie Kianzad", "Division": "Bantamweight", "Age": 29, "Wins": 14, "Losses": 5, "Title Reigns": 0, "Country": "Sweden"},
    {"Name": "Sijara Eubanks", "Division": "Bantamweight", "Age": 35, "Wins": 7, "Losses": 5, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Nicco Montano", "Division": "Bantamweight", "Age": 31, "Wins": 4, "Losses": 3, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Jessica-Rose Clark", "Division": "Bantamweight", "Age": 32, "Wins": 10, "Losses": 6, "Title Reigns": 0, "Country": "Australia"},
    {"Name": "Gina Mazany", "Division": "Bantamweight", "Age": 32, "Wins": 7, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Shana Dobson", "Division": "Bantamweight", "Age": 31, "Wins": 4, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Mara Romero Borella", "Division": "Flyweight", "Age": 34, "Wins": 12, "Losses": 8, "Title Reigns": 0, "Country": "Italy"},
    {"Name": "Gina Carano", "Division": "Featherweight", "Age": 38, "Wins": 7, "Losses": 1, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Cris Cyborg", "Division": "Featherweight", "Age": 35, "Wins": 23, "Losses": 2, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Megan Anderson", "Division": "Featherweight", "Age": 31, "Wins": 11, "Losses": 4, "Title Reigns": 0, "Country": "Australia"},
    {"Name": "Felicia Spencer", "Division": "Featherweight", "Age": 30, "Wins": 8, "Losses": 2, "Title Reigns": 0, "Country": "Canada"},
    {"Name": "Zarah Fairn", "Division": "Featherweight", "Age": 34, "Wins": 6, "Losses": 4, "Title Reigns": 0, "Country": "France"},
    {"Name": "Danyelle Wolf", "Division": "Featherweight", "Age": 37, "Wins": 1, "Losses": 0, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Leah Letson", "Division": "Featherweight", "Age": 28, "Wins": 5, "Losses": 2, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Norma Dumont", "Division": "Featherweight", "Age": 30, "Wins": 5, "Losses": 1, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Josiane Nunes", "Division": "Featherweight", "Age": 27, "Wins": 8, "Losses": 1, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Ailin Perez", "Division": "Featherweight", "Age": 28, "Wins": 7, "Losses": 1, "Title Reigns": 0, "Country": "Argentina"},
    {"Name": "Aspen Ladd", "Division": "Featherweight", "Age": 26, "Wins": 9, "Losses": 1, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Pannie Kianzad", "Division": "Featherweight", "Age": 29, "Wins": 14, "Losses": 5, "Title Reigns": 0, "Country": "Sweden"},
    {"Name": "Sijara Eubanks", "Division": "Featherweight", "Age": 35, "Wins": 7, "Losses": 5, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Nicco Montano", "Division": "Featherweight", "Age": 31, "Wins": 4, "Losses": 3, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Jessica-Rose Clark", "Division": "Featherweight", "Age": 32, "Wins": 10, "Losses": 6, "Title Reigns": 0, "Country": "Australia"},
    {"Name": "Gina Mazany", "Division": "Featherweight", "Age": 32, "Wins": 7, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Shana Dobson", "Division": "Featherweight", "Age": 31, "Wins": 4, "Losses": 4, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Mara Romero Borella", "Division": "Featherweight", "Age": 34, "Wins": 12, "Losses": 8, "Title Reigns": 0, "Country": "Italy"},
    {"Name": "Gina Carano", "Division": "Featherweight", "Age": 38, "Wins": 7, "Losses": 1, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Cris Cyborg", "Division": "Featherweight", "Age": 35, "Wins": 23, "Losses": 2, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Megan Anderson", "Division": "Featherweight", "Age": 31, "Wins": 11, "Losses": 4, "Title Reigns": 0, "Country": "Australia"},
    {"Name": "Felicia Spencer", "Division": "Featherweight", "Age": 30, "Wins": 8, "Losses": 2, "Title Reigns": 0, "Country": "Canada"},
    {"Name": "Zarah Fairn", "Division": "Featherweight", "Age": 34, "Wins": 6, "Losses": 4, "Title Reigns": 0, "Country": "France"},
    {"Name": "Danyelle Wolf", "Division": "Featherweight", "Age": 37, "Wins": 1, "Losses": 0, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Leah Letson", "Division": "Featherweight", "Age": 28, "Wins": 5, "Losses": 2, "Title Reigns": 0, "Country": "USA"},
    {"Name": "Norma Dumont", "Division": "Featherweight", "Age": 30, "Wins": 5, "Losses": 1, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Josiane Nunes", "Division": "Featherweight", "Age": 27, "Wins": 8, "Losses": 1, "Title Reigns": 0, "Country": "Brazil"},
    {"Name": "Ailin Perez", "Division": "Featherweight", "Age": 28, "Wins": 7, "Losses": 1, "Title Reigns": 0, "Country": "Argentina"}
]

# Path to the CSV file
csv_file_path = 'public/ufcwordle.csv'

# Read existing data to check for duplicates
existing_fighters = set()
with open(csv_file_path, mode='r', newline='') as file:
    reader = csv.DictReader(file)
    for row in reader:
        existing_fighters.add(row['Name'])

# Append new fighters if they are not duplicates
with open(csv_file_path, mode='a', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=["Name", "Division", "Age", "Wins", "Losses", "Title Reigns", "Country"])
    
    # Append new fighters
    for fighter in new_fighters:
        if fighter['Name'] not in existing_fighters:
            writer.writerow(fighter)

print("New UFC fighters have been added to the CSV file.") 